### ISSUE TITLE
Review: Step-by-step tutorial on how to reproduce the results

### ISSUE THREAD

**Issue by cthoyt** [fanavarro/lexical-analysis-obo-foundry#1]
The README is not sufficient to reproduce the results that are generated by this repository. It should be significantly improved to include information about what versions of Java, R, etc. are used, how to install the packages that were used in each. Ideally, this should be a series of non-interactive commands in the shell.

**Comment by fanavarro** [comment]
I have included a step-by-step tutorial, including the concrete versions of the used software. I think the results can be reproduced with this included tutorial. Nonetheless, feel free to reopen this issue if you see any missing point.
