### ISSUE TITLE
Review: make sure scripts don't have any hard coded file paths

### ISSUE THREAD

**Issue by cthoyt** [fanavarro/lexical-analysis-obo-foundry#3]
For example, the script https://github.com/fanavarro/lexical-analysis-obo-foundry/blob/main/getMetricsCandidates.sh assumes the data files are in a certain place. Typically in a code review, I will check all files, but I'm a bit stuck because of #1, so this will have to wait until a second round of review

**Comment by fanavarro** [comment]
I've checked that all of the hard coded file paths are relative paths. There should not be any problem on reproducibility if the instructions included in the readme are followed. Nonetheless, if you have any problem about this, please reopen this issue and we can follow up this conversation.
