### ISSUE TITLE
Review: use standard layout for code

### ISSUE THREAD

**Issue by cthoyt** [fanavarro/lexical-analysis-obo-foundry#5]
Typically, code lives in a folder called `src/` and data in a folder called `data/`, or something like that. As it is, the repository has many files and folders in the top level that make it hard to navigate

**Comment by fanavarro** [comment]
I have organized the repository in three folders. As explained in the readme:

-  The **data** folder contains several files with the links to download the ontologies. This folder will contain the ontologies  after downloading them through the corresponding script.
- The **scripts** folder contained the R and Bash scripts used to run our analysis.
- The **results** folder contains different files resulting of applying our scripts.
