### ISSUE TITLE
Review: provide source code for metric.jar

### ISSUE THREAD

**Issue by cthoyt** [fanavarro/lexical-analysis-obo-foundry#6]
I assume the https://github.com/fanavarro/lexical-analysis-obo-foundry/blob/main/metrics.jar was used to run the analysis, however, to check the correctness of scientific work, the source code must be made available. Is this the same code used in your previous work on SNOMED CT? Perhaps there is a corresponding repository for it. Please include this information in the README, and we can also start a code review in that repository.

**Comment by fanavarro** [comment]
I've released the source code for metrics.jar at [https://github.com/fanavarro/ontology-metrics](https://github.com/fanavarro/ontology-metrics). I've also included this information in the readme file of this repository.

The code was slightly modified with respect to the code used for SNOMED CT. Nonetheless, it should provide the same results.
