### ISSUE TITLE
Review: missing R scripts

### ISSUE THREAD

**Issue by cthoyt** [fanavarro/lexical-analysis-obo-foundry#7]
I do not see any of the R scripts that were mentioned in the paper. Please include them as well as instructions on how to run them.

**Comment by fanavarro** [comment]
I have included the [R script](https://github.com/fanavarro/lexical-analysis-obo-foundry/blob/main/scripts/data_analysis.R) that I used for the statistical analysis.

Thanks to your advice about reproducibility, we discovered an issue about the random seeds used by the R library pvclust when obtained the dendrograms. Concretely, we were setting the seed before each pvclust execution with the R function `set.seed`. Nonetheless, it seems to be that pvclust needs the seed through an argument passed to the funcion. By using the parameter `iseed` when calling pvclust, this reproducibility issue disappear.

As a consequence of this, the dendrograms obtained now slightly differs from the original ones. Nonetheless, these differences does not affect the main discussions and results of the article.
